services:
  - type: web
    name: stock-dashboard-api-adriel03
    runtime: node
    plan: free
    branch: deployement
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MASSIVE_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
